```{r}
library (EmissV)
library (osmdata)
library (sf)
```
```{r}
city <- "accra"
region_shape <- getbb (place_name = city, format_out = "polygon")
if (is.list (region_shape))
    region_shape <- region_shape [[1]]
dat <- opq (bbox = city) %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sf (quiet = FALSE) %>%
    osmdata::trim_osmdata (region_shape) %>%
    osmdata::osm_poly2line () %>%
    magrittr::extract2 ("osm_lines")
saveRDS (dat, file = "../accra-hw.Rds")
```
```{r}
city <- "accra"
bb <- getbb (city)
lonlat2UTM <- function(lonlat)
{
    utm <- (floor ( (lonlat [1] + 180) / 6) %% 60) + 1
    if (lonlat [2] > 0)
        utm + 32600
    else
        utm + 32700
}
utm <- lonlat2UTM (apply (bb, 1, mean))

url <- paste0 ("https://github.com/ATFutures/who-data/releases/download/",
               "v0.0.2-worldpop-tif-gha-npl/accra.2fpopdens.2fGHA15adj_040213.tif")
download.file (url, "../accra-pop.tif", mode = "wb")
ras <- raster::raster ("../accra-pop.tif") %>%
    raster::crop (raster::extent (bb)) %>%
    as ("SpatialPolygons") %>%
    st_as_sf ()

dat <- readRDS (file = "../accra-hw.Rds")
dat <- dat [dat$highway %in% c ("motorway", "trunk", "primary",
                                "secondary", "teritary"), ]

s <- streetDist (emission = 1, dist = c (1, 0, 0, 0, 0), grid = ras,
                 osm = dat, epsg = utm)
```
